### ISSUE TITLE
RadioButton widget

### ISSUE THREAD

**Issue by leovanhaaren** [GiancarloCode/form_bloc#1]
Hi, awesome package! Could you please add a RadioButton widget?

**Comment by GiancarloCode** [comment]
@leovanhaaren Thank you, I'm glad you find it useful. 😀

I have other improvements that will be published in 2 days, so I will also add RadioButton Widget. 🎉

If you have another request do not hesitate to do it. 👍

It would also be useful if you could share how you are using it, to check if we can improve the package. 😁

For example, in the next version I will add percent to the form state so that it can also be used in forms that carry out long processes and want to show current progress. 🔥🔥🔥

**Comment by GiancarloCode** [comment]
@leovanhaaren Now you can use `RadioButtonGroupFieldBlocBuilder` in `flutter_form_bloc` v0.2.0 🔥
