### ISSUE TITLE
Will "FlutterFormBloc" and "FormBloc" keep updating?

### ISSUE THREAD

**Issue by ignaciolopez12** [GiancarloCode/form_bloc#102]
haven't seen interaction from Giancarlo, the author of the package, for a long time. On his YouTube video channel he does not respond and has uploaded videos about making money (which is also called henry code)
I find it strange

**Comment by GiancarloCode** [comment]
Hello, yes, they will be updated, unfortunately these last weeks I have not had time, and the pull request that I want to make changes the core to make it more testable and extensible, but it takes a little time, but more or less in 1 or 2 weeks. I will spend time :).

Equally PRs are welcome while ;)

P.D. Regarding the spanish channel, simply the main theme of the channel has changed, since I will not upload programming content for a while.

**Comment by ignaciolopez12** [comment]
> Hello, yes, they will be updated, unfortunately these last weeks I have not had time, and the pull request that I want to make changes the core to make it more testable and extensible, but it takes a little time, but more or less in 1 or 2 weeks. I will spend time :).
> 
> Equally PRs are welcome while ;)
> 
> P.D. Regarding the spanish channel, simply the main theme of the channel has changed, since I will not upload programming content for a while.


Ahh great, I'm calm then! Thank you

**Comment by GiancarloCode** [comment]
If you have feature requests, leave them as issues, and then I'll try to integrate everything :)
