### ISSUE TITLE
feature: read-only forms / read-only fields?

### ISSUE THREAD

**Issue by ayushin** [GiancarloCode/form_bloc#110]
Hi,

Would it be a good idea to support read-only forms and fields right outside of the box controlled from the form bloc?

This would allow using the same UI code for lets say users who do and do not have editing access to the data.

I was thinking isReadOnly on the FormBloc constructor with the subsequent logic in the right places?

**Comment by JulianSwales** [comment]
So, has anyone got a work around for this? I now have a form that gets presented back to the user, for editing, BUT certain fields they are not allowed to change.. I'd like to not have to use different fields in the form for this since I already identify in onLoading() the state of what each field should be.. Anyone have a work around/solution for this missing feature?

**Comment by JulianSwales** [comment]
Ok, I take back my comment above.. I see that readOnly is implemented in the builder.. This will work for me.. Thank you.. I was trying it in the field...

**Comment by surister** [comment]
For anyone wondering how to make a read-only field, in the builder you can use readOnly as Julian said, 

```flutter
          TextFieldBlocBuilder(
            readOnly: true,
            textFieldBloc: wizardFormBloc.price,
            keyboardType: TextInputType.multiline,
            maxLines: null,
            decoration: InputDecoration(
              labelText: 'Precio',
              prefixIcon: Icon(Icons.euro_symbol),
            ),
          ),
```
