### ISSUE TITLE
Do you follow Semantic Versioning ?

### ISSUE THREAD

**Issue by sm2017** [GiancarloCode/form_bloc#19]
I am using `flutter_form_bloc` in my flutter project , Today I upgrade it from `0.5.0` to `0.10.2`
It seems there is a breaking change

In `onSubmitting` I used  `yield state.toSuccess(myString);` many times ,after upgrading I have to change it to `yield state.toSuccess(successResponse: response);`

**Comment by sm2017** [comment]
Also I used `FieldBlocBase` as a type now 
```
The name 'FieldBlocBase' isn't a type so it can't be used as a type argument.

Try correcting the name to an existing type, or defining a type named 'FieldBlocBase'.Open documentation
```

**Comment by GiancarloCode** [comment]
Semantic Versioning is being used, but since we still don't have a stable version, I have been a bit permissive.

Although with the 0.10.y, some functionalities have been added that previously did not allow to have a stable version.  Therefore, we will have a stable version soon.
___
In the [CHANGELOG](https://github.com/GiancarloCode/form_bloc/blob/master/packages/form_bloc/CHANGELOG.md) you can see most of the changes.

* `state.toSuccess()` now receives more parameters that allow it to be simple to be able to submit the same form several times or use them as a CRUD, as you can see in this [example](https://github.com/GiancarloCode/form_bloc/blob/191ef9e22b07b8ee354a28a6116f2398a95094f6/packages/flutter_form_bloc/example/lib/forms/crud_form_bloc.dart#L32).
* `FieldBlocBase` changed its name to `SingleFieldBloc`, since as of version `0.10.y` we can dynamically add/remove `fieldBlocs`  to/from the `FormBloc`, so `GroupFieldBloc` and `FieldBlocList` are also added to support complex forms. You can see an example: [BLoC](https://github.com/GiancarloCode/form_bloc/blob/master/packages/flutter_form_bloc/example/lib/forms/dynamic_fields_form_bloc.dart) - [UI](https://github.com/GiancarloCode/form_bloc/blob/master/packages/flutter_form_bloc/example/lib/forms/dynamic_fields_form.dart).
___
* If you have any questions during your migration you can ask me and I will gladly help you.

* And as someone who has used `form_bloc` for a while now, I would like to know your opinion about the new version.

**Comment by sm2017** [comment]
@GiancarloCode I migrate feom react-native to flutter
In react ecosystem, there is a great library named https://github.com/final-form/react-final-form , it's very nice for inspiration

form_bloc library is one of the best library I used, it's clean and easy to use and manage, Upgrading to latest version is easy too, I think newer version is more better

Thank you very much

**Comment by GiancarloCode** [comment]
@sm2017 Thanks, I have reviewed react-final-form and had some ideas :).
 I am also trying to make it less boilerplate for get fieldblocs and their values.

It would be great if you could give your opinion in [this issues](https://github.com/GiancarloCode/form_bloc/issues?q=is%3Aissue+is%3Aopen+label%3A%22feedback+wanted%22) 
And if you feel that some feautures are missing you can create the issue.

Thank you :)
