### ISSUE TITLE
Feature request: More customizable DropdownField

### ISSUE THREAD

**Issue by sm2017** [GiancarloCode/form_bloc#225]
Can you please change signature of `itemBuilder` of `DropdownFieldBlocBuilder` to let us customize rendered value?
Currently `itemBuilder` returns `String` , By returning `Widget` and wrapping  `itemBuilder` with `DefaultTextStyle` we have more customizable `DropdownField`

Also it's nice to have a param that let us now the dropdown is open or not

```dart
typedef FieldBlocStringItemBuilder<Value> = Widget Function(BuildContext context, Value value, bool isMenuOpen);
```

**Comment by sm2017** [comment]
@WahdanZ Can you please reply?

**Comment by GiancarloCode** [comment]
Hi @sm2017 , it's been a while, I hope you are well.

Respect the ItemBuilder That would be a breaking change, but it seems reasonable to me, but it will not be implemented this week.

It would be implemented with https://github.com/GiancarloCode/form_bloc/issues/227

And since I know you have been using the library for a long time, I would like your comments there.

___

and what would be the use case to know if the dropdown is open or not?

**Comment by sm2017** [comment]
@GiancarloCode thank you very much, I'm so glad to see you here
I have a **budget** dropdown, each budget has a title, min value and max value
I want to show only budget title when the dropdown is closed, and show min and max value as a subtitle too when dropdown is open
