### ISSUE TITLE
[Proposal] Add method to FormBlocState to get the current value of FieldBloc easily

### ISSUE THREAD

**Issue by GiancarloCode** [GiancarloCode/form_bloc#36]
Currently when you want to obtain the current value of a  `FieldBloc` you must get the `FieldBloc` and then call `value` property.
```dart
state.fieldBlocFromPath('email').asTextFieldBloc.value;
state.fieldBlocFromPath('email').asSelectFieldBloc<T>().value;
```

The proposal is add method that get the current value of a `FieldBloc` without access to the `FieldBloc` before,, reducing the amount of code.

## Option 1:
```dart
state.fieldBlocValue<T>('path');
state.fieldBlocValue('path');
state.fieldBlocValue<String>('path');
state.fieldBlocValue<DateTime>('path');
```

## Option 2:

```dart
state.getFieldBlocValue<T>('path');
state.getFieldBlocValue('path');
state.getFieldBlocValue<String>('path');
state.getFieldBlocValue<DateTime>('path');
```

## Option 3:

```dart
state.findFieldBlocValueOf<T>('path');
state.findFieldBlocValueOf('path');
state.findFieldBlocValueOf<String>('path');
state.findFieldBlocValueOf<DateTime>('path');
```

## Option 4: (This will be added in form_bloc 0.10.5)

```dart
state.valueOf<T>('path');
state.valueOf('path');
state.valueOf<String>('path');
state.valueOf<DateTime>('path');
```
#### The generic type `T` is for have static analysis.
___

**Comment by BreX900** [comment]
If we take BuildContext as an example and then follow the guidelines, the correct method name would be of the `state.findFieldBlocValue <T> ('name')`
Since neither of the two proposals exactly follow the guidelines we might as well take the shorter `fieldBlocValue`
https://dart.dev/guides/language/effective-dart/design#avoid-starting-a-method-name-with-get
This is my opinion

**Comment by GiancarloCode** [comment]
@BreX900 Thanks for your opinion, I would like you to inform me a bit more because you think it should be `findFieldBlocValue`, that name had not occurred to you :).

The `getFieldBlocValue` option is dropped.

And also while looking for information about it, I think that it may be `valueOf <T> ('path')` makes quite a lot of sense, like Inherited widgets / provider syntax.
what do you think?

 And if you can also check https://github.com/GiancarloCode/form_bloc/issues/33 which is quite related.

thanks :)

**Comment by BreX900** [comment]
@GiancarloCode I simply thought of comparing `BuildContext` with` FormBlocState`. Since they both contain something Widget and FieldBloc `findFieldBlocValue` made sense. I remember `BuildContext.findAncestorStateOfType`.
So if we take a cue it could be:
`FindFieldBlocValueOf <T> (path)`

In my opinion, `FormBlocState` is more similar to` BuildContext` and not to `Provider`. Because `FormBlocState` contains information, it does not search for information in something like` Provider` does.

I think `state.valueOf <T> (path)` is also fine and I recommend adding `state.fieldBlocOf <T extends FieldBloc> (path)`.

**Comment by GiancarloCode** [comment]
Thanks
You are right `FormBlocState` is like the `buildContext`, but I was referring more that the syntax is more friendly, since they all do the same thing, obtain the nearest `T`.

[findAncestorStateOfType<T extends State<StatefulWidget>>](https://api.flutter.dev/flutter/widgets/BuildContext/findAncestorStateOfType.html)
> Returns the State object of the nearest ancestor StatefulWidget widget that is an instance of the given type T...

[Provider.of](https://pub.dev/documentation/provider/latest/provider/Provider/of.html)
> Obtains the nearest `Provider<T>` up its widget tree and returns its value.

[dependOnInheritedWidgetOfExactType<T extends InheritedWidget>](https://api.flutter.dev/flutter/widgets/BuildContext/dependOnInheritedWidgetOfExactType.html)
> Obtains the element corresponding to the nearest widget of the given type T,..

I think it will be added `state.valueOf<T>(path)`
___

`state.fieldBlocOf<T extends FieldBloc>(path)` can be added but has some boilerplate

```dart
state.fieldBlocOf<TextFieldBloc>(path)
```
I think it can be replaced by the following methods.

```dart
state.textFieldBlocOf('path');
state.booleanFieldBlocOf('path');
state.selectFieldBlocOf<T>('path');
state.multiSelectFieldBlocOf<T>('path');
state.inputFieldBlocOf<T>('path');
state.groupFieldBlocOf('path');
state.fieldBlocListOf('path');
```

**Comment by GiancarloCode** [comment]
Option 4 will be added in form_bloc 0.10.5 🔥

```dart
state.valueOf<T>(path)
```

**Comment by GiancarloCode** [comment]
🔥 Added in form bloc v0.11.0 🔥
