### ISSUE TITLE
FieldBlocs are null on first-time build

### ISSUE THREAD

**Issue by JTorrus** [GiancarloCode/form_bloc#52]
I have this piece of code for a Sign In page

```dart
...

@override
 Widget build(BuildContext context) {
    return FormBlocListener<SignUpValidationBloc, String, AuthError>(
      formBloc: signUpBloc,
      onLoading: (context, state) => showDialog(
        context: context,
        builder: (context) => Container(
          height: 100,
          width: 100,
          child: Center(
            child: CupertinoActivityIndicator(),
          ),
        ),
      ),
     ...
      child: Column(
        children: <Widget>[
          Padding(
            padding: const EdgeInsets.only(
              top: Styles.kLargePadding,
              bottom: Styles.kLargePadding,
            ),
            child: _buildFields(_signUpValidationBloc),
          ),
         ...
        ],
      ),
    );
  }

...

Widget _buildFields(SignUpValidationBloc signUpBloc) {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: Styles.kLargePadding),
      child: Column(
        children: <Widget>[
          AuthTextForm(
            hintText: AppLocalizations.of(context).translate("signup_email"),
            action: TextInputAction.next,
            onFieldSubmitted: (_) =>
                FocusScope.of(context).requestFocus(_passwordNode),
            focusNode: _emailNode,
            type: TextInputType.emailAddress,
            bloc: signUpBloc.state.textFieldBlocOf("email"),
          ),
          SizedBox(
            height: Styles.kSemiLargePadding,
          ),
          AuthTextForm(
            hintText: AppLocalizations.of(context).translate("signup_password"),
            isPassword: true,
            action: TextInputAction.done,
            focusNode: _passwordNode,
            bloc: signUpBloc.state.textFieldBlocOf("password"),
            onFieldSubmitted: (_) => signUpBloc.submit(),
          ),
        ],
      ),
    );
  }
```

As you can see, I build two custom TextFields at `_buildFIelds` method passing their corresponding FieldBloc as an argument (`bloc`) for each Widget.

Problem is the textfields do not appear when building for the first time. It looks like the FieldBlocs are null at this point. But if I hot reload, they appear.

I don't know if I'm doing something wrong but I'm having a hard time figuring out how to solve this.

**Comment by GiancarloCode** [comment]
Hello, I recommend that you look at the simple example on the web, since version 0.11.0 using 
 `... FieldBlocOf` is only recommended for very complex cases involving dynamic fields.

If you do the migration you will have a code with a strong type and much cleaner.

https://giancarlocode.github.io/form_bloc/#/simple_example

__

Because the field blocs are dynamically added, in the first `search / find` you will not find it, in terms of UI it is imperceptible since the widget is built, it has already found it.

Your mistake is because you are not accessing the field bloc through the state of a `BlocBuilder<FormBloc, FormBlocState>`, but directly using the state property of the form bloc.
if you want it to work, you need  to access thought state of   `BlocBuilder`.

```dart
...
BlocBuilder<FormBloc, FormBlocState>(
  bloc: formBloc,
  builder: _buildFields(state),
),
...
Widget _buildFields(FormBlocState formBlocState) 
...
          AuthTextForm(
            hintText: AppLocalizations.of(context).translate("signup_email"),
            action: TextInputAction.next,
            onFieldSubmitted: (_) =>
                FocusScope.of(context).requestFocus(_passwordNode),
            focusNode: _emailNode,
            type: TextInputType.emailAddress,
            bloc: formBlocState.textFieldBlocOf("email"),
          ),
```
### But I recommend that you migrate, you will have an increase in performance, and also a cleaner and safer code.

Let me know if you have any doubt.

**Comment by JTorrus** [comment]
Oh, I thought about that just right now, you are right, I'm not accessing the `state` properly, my bad! 

And yeah, I will take a look at your documentation in order to have a cleaner code. I recently upgraded from an older version so I was a bit confused about the `fieldBlocOf` method and its usage so thank you so much for your guidance. 

Since the main issue is solved, I'm gonna close this.
