### ISSUE TITLE
[TextFieldBlocBuilder] Unpleasant opening of the keyboard

### ISSUE THREAD

**Issue by BreX900** [GiancarloCode/form_bloc#56]
The scenario is as follows: `TextFieldBlocBuilder` with` suffixButton: SuffixButton.obscureText`.
When you press `suffixButton` if the keyboard is closed it is opened. This shouldn't be happening
Or am I wrong?

**Comment by GiancarloCode** [comment]
For now it is the expected behavior
https://github.com/flutter/flutter/issues/36948#issuecomment-515119841
And the PR that fixes it is paused
https://github.com/flutter/flutter/pull/38722

We could look at an alternative solution like [this](https://github.com/flutter/flutter/issues/39376) but I'm not sure

**Comment by GiancarloCode** [comment]
I close for now.
