### ISSUE TITLE
Which package to install?

### ISSUE THREAD

**Issue by ignaciolopez12** [GiancarloCode/form_bloc#90]
Which package to install? "flutter_form_bloc" or "form_bloc"? 
They are the same? In what differences does it have?

**Comment by GiancarloCode** [comment]
`form_bloc` is the core (Have all  the blocs) and is a pure dart library. (you can use it also in any dart platform or framework like Flutter. AngularDart)

`flutter_form_bloc` have flutter built-in widgets to easily use the blocs of form_bloc (but also export form_bloc)

If you have different packages in your apps like when using DDD or layered architectures, you may not want to have flutter as a dependency in this packages.
In those cases you can use form_bloc at the Domain or Business Logic layer, and use flutter_form_bloc in your presentation layer.

But if you only have one package and it is coupled to flutter use only flutter_form_bloc.

You must remember that the BLoC pattern aims to share code between platforms, that's why there are 2 packages :).
